/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package yazilimmuhproje.app;
import java.util.ArrayList;


import yazilimmuhproje.list.LinkedList;

import static yazilimmuhproje.utilities.StringUtils.join;
import static yazilimmuhproje.utilities.StringUtils.split;
import static yazilimmuhproje.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
    public static boolean search(ArrayList<Integer> array, int e){
        System.out.println("İnside search");
        if(array==null) return false;
        for(int elt:array){
            if(elt==e) return true;

        }
        return false;

    }
    public Object GetGreeting() {
        return null;
    }
}
